feat: change instance specific dimensions in aggregated metrics
elastic/apm-aggregation pull request #103
Opened 2023-09-06 10:03 UTC by kruskall

Add service instance transaction metrics and change instance specific dimensions in aggregated metrics

Related to https://github.com/elastic/apm-server/issues/11266

2023-09-06 11:17 UTC, carsonip requested changes

2023-09-06 11:17 UTC, carsonip commented on aggregators/merger.go
> +// mergeTransactionGroups merges service instance transaction aggregation groups for two combined metrics
```suggestion
// mergeServiceInstanceTransactionGroups merges service instance transaction aggregation groups for two combined metrics
```

2023-09-06 11:17 UTC, carsonip commented on aggregators/converter.go
> +	mb.keyedServiceInstanceTransactionMetrics.Key = &mb.serviceInstanceTransactionAggregationKey
Test failures are caused by missing reset on line 305
```
mb.keyedServiceInstanceTransactionMetricsSlice = mb.keyedServiceInstanceTransactionMetricsSlice[:0]
```

I hate github code review UI, can't leave comments on unchanged lines.

2023-09-07 05:41 UTC, lahsivjar approved these changes
Code LGTM!

2023-09-07 05:41 UTC, lahsivjar commented on aggregators/converter.go
> +	// There can be at most ? service instance transaction metric per event.
```suggestion
	// There can be at most 1 service instance transaction metric per event.
```

The `partitionedMetricsBuilder` will build `CombinedMetrics` for a single `APMEvent`. Thus, there will only be 1 service instance transaction metric per APMEvent.

2023-09-08 09:41 UTC, carsonip approved these changes

2023-09-08 09:41 UTC, carsonip commented on aggregators/merger.go
> +// considering max transaction groups and max transaction groups per service limits.
```suggestion
// considering max service instance transaction groups and max service instance transaction groups per service limits.
```

2023-09-08 12:12 UTC, merged